In [104]:
""" This is basic recommendation which uses apriori algorithom. This application will suggest learning materials
of e-learning portal """
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from apyori import apriori # you can download this module
import seaborn as sns
%matplotlib inline

In [105]:
data_session_frame=pd.read_excel('sample.xls',sheet_name='LS_Data') #sample excel file

In [141]:
data_session_frame=(data_session_frame.groupby('Session_Id').filter(lambda x: len(x) >= 2))#accept only the sesssion which goes through once02
print('unique Product in dataset = ', len(data_session_frame.VisitedMaterials.unique()))
Uniq_VisitedMaterials= data_session_frame.VisitedMaterials.unique().tolist()  
session_ids=data_session_frame.Session_Id.unique().tolist()
row_array=np.array(len(Uniq_VisitedMaterials))
session_ids
df = pd.DataFrame(columns=Uniq_VisitedMaterials, index=session_ids)
for id in session_ids:
    session_row=data_session_frame.loc[data_session_frame['Session_Id']==id]['VisitedMaterials']
    df.loc[id]['Session_Id']=id
    for m_value in session_row:
         df.loc[id][m_value]=m_value

df.shape
records=[]
for i in range(0,df.shape[0]):
    records.append([str(df.values[i,j]) for j in range(0,df.shape[1])])  
    
association_rules = apriori(records, min_support=0.0045, min_confidence=0.2, min_lift=1, min_length=2)
association_results = list(association_rules)

recommand_df = pd.DataFrame(columns=('Items','Antecedent','Consequent','Support','Confidence','Lift'))
Support =[]
Confidence = []
Lift = []
Items = []
Antecedent = []
Consequent=[]
for RelationRecord in association_results:
    for ordered_stat in RelationRecord.ordered_statistics:
        Support.append(RelationRecord.support)
        Items.append(RelationRecord.items)
        Antecedent.append(ordered_stat.items_base)
        Consequent.append(ordered_stat.items_add)
        Confidence.append(ordered_stat.confidence)
        Lift.append(ordered_stat.lift)
recommand_df['Items'] = list(map(set, Items))                                   
recommand_df['Antecedent'] = list(map(set, Antecedent))
recommand_df['Consequent'] = list(map(set, Consequent))
recommand_df['Support'] = Support
recommand_df['Confidence'] = Confidence
recommand_df['Lift']= Lift
recommand_df

unique Product in dataset =  8

                 Items     Antecedent Consequent   Support  Confidence  Lift
0                 {M1}             {}       {M1}  0.571429    0.571429  1.00
1                {M14}             {}      {M14}  0.285714    0.285714  1.00
2                 {M2}             {}       {M2}  0.571429    0.571429  1.00
3                 {M3}             {}       {M3}  0.285714    0.285714  1.00
4                {nan}             {}      {nan}  1.000000    1.000000  1.00
..                 ...            ...        ...       ...         ...   ...
115  {M3, M2, nan, M1}      {M3, nan}   {M2, M1}  0.285714    1.000000  1.75
116  {M3, M2, nan, M1}   {M3, M2, M1}      {nan}  0.285714    1.000000  1.00
117  {M3, M2, nan, M1}  {M2, nan, M1}       {M3}  0.285714    0.500000  1.75
118  {M3, M2, nan, M1}  {M3, nan, M1}       {M2}  0.285714    1.000000  1.75
119  {M3, M2, nan, M1}  {M3, M2, nan}       {M1}  0.285714    1.000000  1.75

[120 rows x 6 columns]

In [107]:
data_session_material_df=pd.DataFrame(columns=Uniq_VisitedMaterials)
data_session_material_df

Empty DataFrame
Columns: [M1, M2, M3, M7, M14, M 6, M16, M9]
Index: []

In [144]:
records_len=[['M1', 'M2', 'M3'],
 ['M1', 'M2'],
 [ 'M7', 'M14', 'M 6'],
 ['M14', 'M16'],
 ['M1', 'M2', 'M3'],
 ['M1', 'M2'],
 ['M9'],
 ['M1', 'M2', 'M3'],
 ['M1', 'M2'],
 [ 'M7', 'M14', 'M 6'],
 ['M14', 'M16'],
 ['M1', 'M2', 'M3'],
 ['M1', 'M2'],
 [ 'M9']]
association_rules = apriori(records_len, min_support=0.0045, min_confidence=0.2, min_lift=1, min_length=2)
association_results = list(association_rules)
recommand_df = pd.DataFrame(columns=('Items','Antecedent','Consequent','Support','Confidence','Lift'))
Support =[]
Confidence = []
Lift = []
Items = []
Antecedent = []
Consequent=[]
for RelationRecord in association_results:
    for ordered_stat in RelationRecord.ordered_statistics:
        Support.append(RelationRecord.support)
        Items.append(RelationRecord.items)
        Antecedent.append(ordered_stat.items_base)
        Consequent.append(ordered_stat.items_add)
        Confidence.append(ordered_stat.confidence)
        Lift.append(ordered_stat.lift)
recommand_df['Items'] = list(map(list, Items))                                   
recommand_df['Antecedent'] = list(map(list,Antecedent))
recommand_df['Consequent'] = list(map(list, Consequent))
recommand_df['Support'] = Support
recommand_df['Confidence'] = Confidence
recommand_df['Lift']= Lift
recommand_df

             Items  Antecedent    Consequent   Support  Confidence  Lift
0             [M1]          []          [M1]  0.571429    0.571429  1.00
1            [M14]          []         [M14]  0.285714    0.285714  1.00
2             [M2]          []          [M2]  0.571429    0.571429  1.00
3             [M3]          []          [M3]  0.285714    0.285714  1.00
4       [M14, M 6]       [M 6]         [M14]  0.142857    1.000000  3.50
5       [M14, M 6]       [M14]         [M 6]  0.142857    0.500000  3.50
6        [M7, M 6]       [M 6]          [M7]  0.142857    1.000000  7.00
7        [M7, M 6]        [M7]         [M 6]  0.142857    1.000000  7.00
8         [M2, M1]          []      [M2, M1]  0.571429    0.571429  1.00
9         [M2, M1]        [M1]          [M2]  0.571429    1.000000  1.75
10        [M2, M1]        [M2]          [M1]  0.571429    1.000000  1.75
11        [M3, M1]          []      [M3, M1]  0.285714    0.285714  1.00
12        [M3, M1]        [M1]          [M3]  0.285714    0.500000  1.75
13        [M3, M1]        [M3]          [M1]  0.285714    1.000000  1.75
14      [M16, M14]       [M14]         [M16]  0.142857    0.500000  3.50
15      [M16, M14]       [M16]         [M14]  0.142857    1.000000  3.50
16       [M7, M14]       [M14]          [M7]  0.142857    0.500000  3.50
17       [M7, M14]        [M7]         [M14]  0.142857    1.000000  3.50
18        [M3, M2]          []      [M3, M2]  0.285714    0.285714  1.00
19        [M3, M2]        [M2]          [M3]  0.285714    0.500000  1.75
20        [M3, M2]        [M3]          [M2]  0.285714    1.000000  1.75
21  [M14, M7, M 6]       [M 6]     [M7, M14]  0.142857    1.000000  7.00
22  [M14, M7, M 6]       [M14]     [M7, M 6]  0.142857    0.500000  3.50
23  [M14, M7, M 6]        [M7]    [M 6, M14]  0.142857    1.000000  7.00
24  [M14, M7, M 6]  [M14, M 6]          [M7]  0.142857    1.000000  7.00
25  [M14, M7, M 6]   [M7, M 6]         [M14]  0.142857    1.000000  3.50
26  [M14, M7, M 6]   [M7, M14]         [M 6]  0.142857    1.000000  7.00
27    [M3, M2, M1]          []  [M3, M2, M1]  0.285714    0.285714  1.00
28    [M3, M2, M1]        [M1]      [M3, M2]  0.285714    0.500000  1.75
29    [M3, M2, M1]        [M2]      [M3, M1]  0.285714    0.500000  1.75
30    [M3, M2, M1]        [M3]      [M2, M1]  0.285714    1.000000  1.75
31    [M3, M2, M1]    [M2, M1]          [M3]  0.285714    0.500000  1.75
32    [M3, M2, M1]    [M3, M1]          [M2]  0.285714    1.000000  1.75
33    [M3, M2, M1]    [M3, M2]          [M1]  0.285714    1.000000  1.75